(function() {
    function initQuickFavorites() {
        // 1. Ensure the popup menu payload container exists on the page
        if (!document.getElementById('my-custom-fav-menu')) {
            fetch('/plugins/quick.favorites/popup.php')
                .then(function(res) { return res.text(); })
                .then(function(html) {
                    var div = document.createElement('div');
                    div.innerHTML = html;
                    document.body.appendChild(div);
                })
                .catch(function(err) { console.error('Failed to load Quick Favorites popup payload:', err); });
        }

        // 2. Find the native Favorites tab generated by the plugin page
        function findMenuItemByText(label) {
            var nodes = document.querySelectorAll('div#menu a, div#menu button');
            for (var i = 0; i < nodes.length; i++) {
                if (nodes[i].textContent.trim() === label) return nodes[i];
            }
            return null;
        }

        var favTab = findMenuItemByText('Favorites') || findMenuItemByText('⭐⭐');
        if (!favTab) return false; // Not rendered yet, retry

        // If not already transformed, clone to drop native Unraid navigation handlers
        if (favTab.id !== 'qf-custom-btn') {
            var cleanTab = favTab.cloneNode(false);
            cleanTab.id = 'qf-custom-btn';
            cleanTab.href = '#';
            cleanTab.textContent = '⭐⭐';
            cleanTab.setAttribute('title', 'Quick Favorites');
            cleanTab.removeAttribute('onclick');

            favTab.replaceWith(cleanTab);
            favTab = cleanTab;
        }

        // 3. Move its wrapper container to the absolute end of the menu bar
        var wrapper = favTab.closest('.nav-item') || favTab.parentElement;
        var parent = wrapper ? wrapper.parentNode : null;
        if (parent && parent.lastElementChild !== wrapper) {
            parent.appendChild(wrapper);
        }

        // 4. Bind click toggle handler safely
        if (!favTab._qfBound) {
            favTab._qfBound = true;
            favTab.addEventListener('click', function(e) {
                e.preventDefault();
                e.stopPropagation();
                
                var customMenu = document.getElementById('my-custom-fav-menu');
                if (!customMenu) return;

                if (customMenu.style.display === 'block') {
                    customMenu.style.display = 'none';
                } else {
                    customMenu.style.display = 'block';
                    var rect = favTab.getBoundingClientRect();
                    var menuWidth = customMenu.offsetWidth || 480;
                    var btnCenter = rect.left + window.scrollX + (rect.width / 2);
                    var calculatedLeft = Math.max(15, Math.min(btnCenter - (menuWidth / 2), window.innerWidth - menuWidth - 15));
                    customMenu.style.top = (rect.bottom + window.scrollY + 10) + 'px';
                    customMenu.style.left = calculatedLeft + 'px';
                }
            }, true);
        }
        return true;
    }

    // Aggressive retry loop until Unraid's menu renders on any page
    var attempts = 0;
    var timer = setInterval(function() {
        var success = initQuickFavorites();
        attempts++;
        if (success || attempts >= 50) {
            clearInterval(timer);
        }
    }, 200);
})();

// Global event delegation for script actions inside the popup menu
document.addEventListener('click', function(e) {
    var customMenu = document.getElementById('my-custom-fav-menu');
    if (!customMenu || customMenu.style.display !== 'block') return;

    if (!e.target.closest('#my-custom-fav-menu') && !e.target.closest('#qf-custom-btn')) {
        customMenu.style.display = 'none';
    } else {
        var itemTarget = e.target.closest('.qf-item');
        if (itemTarget) {
            var action = itemTarget.getAttribute('data-action');
            var path = itemTarget.getAttribute('data-path') ? itemTarget.getAttribute('data-path').trim() : '';
            var token = (typeof csrf_token !== 'undefined') ? csrf_token : '';

            if (action === 'script_modal' || action === 'script_background') {
                e.preventDefault(); e.stopPropagation();
                var fullScriptPath = "/boot/config/plugins/user.scripts/scripts/" + path + "/script";
                
                $.post('/plugins/user.scripts/exec.php', {
                    script: fullScriptPath,
                    action: 'intermediate',
                    csrf_token: token
                }, function() {
                    var tmpScriptPath = "/tmp/user.scripts/tmpScripts/" + path + "/script";
                    var targetUrl = (action === 'script_modal') 
                        ? "/plugins/user.scripts/startScript.sh&arg1=" + tmpScriptPath 
                        : "/plugins/user.scripts/backgroundScript.sh&arg1=" + tmpScriptPath;
                    
                    openBox(targetUrl, 'Executing: ' + path, 600, 900, true);
                    customMenu.style.display = 'none'; 
                });
            } 
            else if (action === 'script_log') {
                e.preventDefault(); e.stopPropagation();
                if (!path) return;
                
                var scriptName = path.replace(/^\/+/, '');
                var logWin = window.open('/logging.htm?done=Close', 'qf_log_window', 'width=800,height=600,resizable=yes,scrollbars=yes');
                var fetchUrl = '/plugins/quick.favorites/log_api.php?script=' + encodeURIComponent(scriptName);
                
                fetch(fetchUrl)
                    .then(function(res) { return res.text(); })
                    .then(function(logData) {
                        var checkReady = setInterval(function() {
                            if (logWin && logWin.document && logWin.document.readyState === 'complete') {
                                clearInterval(checkReady);
                                var contentDiv = logWin.document.createElement('div');
                                contentDiv.style.whiteSpace = 'pre-wrap';
                                contentDiv.style.fontFamily = 'monospace';
                                contentDiv.style.padding = '10px';
                                contentDiv.innerHTML = logData; 
                                logWin.document.body.insertBefore(contentDiv, logWin.document.body.firstChild);
                                logWin.scrollTo(0, logWin.document.body.scrollHeight);
                            }
                        }, 50);
                    });
                customMenu.style.display = 'none';
            }
        }
    }
}, true);